### ISSUE TITLE
fail_if_no_peer_cert

### ISSUE THREAD

**Issue by alexk4153** [lukebakken/rabbitmq-users-crl-6LjcEo9cn98#2]
Hey 
first of all thanks for this.
I have tried these instructions
```
docker version
docker compose version
git clone https://github.com/lukebakken/rabbitmq-users-crl-6LjcEo9cn98.git
cd rabbitmq-users-crl-6LjcEo9cn98
git submodule update --init
docker compose build --no-cache --pull
docker compose up --no-color |& tee /tmp/crl-6LjcEo9cn98-logs.txt
```
however I get this error  fail_if_no_peer_cert}}
[crl-6LjcEo9cn98-logs.txt](https://github.com/user-attachments/files/17268512/crl-6LjcEo9cn98-logs.txt)

So I can't really reproduce this code on my Mac.
Could you assist please?

**Comment by unfixa1** [comment]
It looks like you are getting a fail_if_no_peer_cert error when trying to run RabbitMQ's Docker container. This is usually related to certificate verification for SSL/TLS connections.
You can use the tool [servbay](servbay.com) to build a development environment instead of docker to eliminate environment bugs. servbay supports automatic ssl certificate verification

**Comment by lukebakken** [comment]
@unfixa1 - you are not correct. The error is clear:

```
Federation exchange 'federated-direct' in vhost '/' did not connect to exchange 'federated-direct' in vhost '/' on amqps://rmq0.
Reason: {error,
{option,
 server_only,
 fail_if_no_peer_cert}}
```

There is an error in the configuration for my example. Prior to Erlang 26, TLS options were not strictly validated. Now they are. This commit should fix it:

https://github.com/lukebakken/rabbitmq-users-crl-6LjcEo9cn98/commit/0236455b283b6966a08c6c259b0b55ae82d33fc3
